### ISSUE TITLE
Input definition in Splunk Cloud - got Error 500

### ISSUE THREAD

**Issue by fpereszlenyi** [splunk/splunk-add-on-microsoft-azure#14] opened 2022-08-08 11:38 UTC
Hi,

We tried to create Cloud2Cloud intergration from Splunk Cloud to collect data from Azure Cloud.
We could define the Account in configuration, but when we tried to define an input at inputs we got the:
"Failed to load Inputs Page
This is normal on Splunk search heads as they do not require an Input page. Check your installation or return to the [configuration page](https://xxxxxxxxx.splunkcloud.com/en-GB/app/TA-MS-AAD/configuration).

Error: Request failed with status code 500"
error page...

In the Splunk Cloud can put this add-on only to SH (and I checked the add-on splunk Cloud compatible at splunkbase)...

Does this mean that the add-on is not really Splunk Cloud compatible?

Thanks and regards,

Ferenc

<img width="1661" alt="Screenshot 2022-08-08 at 13 36 08" src="https://user-images.githubusercontent.com/6084288/183409498-c6fb8411-eab8-48bd-9e8a-d61b9f7b7ba6.png">

**Comment by JasonConger** [comment] 2022-08-09 21:40
Which version of the Azure add-on is installed?  I noticed the screenshot, the title of the add-on is "Microsoft Azure Add-on for Splunk".  The title changed to "Splunk Add-on for Microsoft Azure" in the latest release (version 4.x).

Also, do you happen to have the Splunk Add-on for Microsoft Cloud Services installed?  There was a [conflict at one time between these 2 add-ons](https://docs.splunk.com/Documentation/AddOns/released/MSCloudServices/ReleaseHistory#Compatibility_7), but that was resolved.  Opening a support case can help uncover the root cause.

**Comment by fpereszlenyi** [comment] 2022-08-11 12:12
Yes, it was installed earlier version. I updated it to latest 4.0.2, but the situation is same... 
![Screenshot 2022-08-11 at 14 11 38](https://user-images.githubusercontent.com/6084288/184130606-52fab48c-c96e-4932-9644-2c6fb8acace5.png)

**Comment by norbertt911** [comment] 2022-09-12 13:39
Hello,

I got the same issue on On-Prime Splunk enterprise 9.0.1. Clean, fresh install of 4.0.2:
![image](https://user-images.githubusercontent.com/54628405/189668733-af70a4fd-be46-412b-bf8e-e28ab843471e.png)

Note: the error code is 404, not 500, but I belive the root cause is the same.

Kind regards,
Norbert

**Comment by JasonConger** [comment] 2022-09-28 15:22
Addressed in 4.0.3

**Closed by JasonConger** 2022-09-28 15:22 UTC
Labels: status: work in progress
