### ISSUE TITLE
Errormin web ui

### ISSUE THREAD

**Issue by saravanakumar-subbiah** [splunk/splunk-add-on-microsoft-azure#8] opened 2022-07-26 07:23 UTC
I am getting error message. while i open AD

Unable to initialize modular input "azure_virtual_network" defined in the app "TA-MS-AAD": Introspecting scheme=azure_virtual_network: script running failed (exited with code 1).. 7/26/2022, 12:48:39 PM

Error: Request failed with status code 500 in webui, any help ?

**Comment by JasonConger** [comment] 2022-07-26 22:46
Was this an in-place upgrade or a clean install?

**Comment by saravanakumar-subbiah** [comment] 2022-07-27 01:58
Clean Install only. After downgrade to 3.1 it is working.

On 27-Jul-2022 4:16 am, Jason Conger ***@***.***> wrote:

Was this an in-place upgrade or a clean install?

**Comment by JasonConger** [comment] 2022-07-27 03:34
What OS and Splunk version are you using?

**Comment by saravanakumar-subbiah** [comment] 2022-07-27 03:55
Windows 2012 server
Splunk 9.0




Saravanakumar. S
Manager - Security Operations
Hand Phone:8754485958

**Comment by JasonConger** [comment] 2022-08-10 16:49
The root cause has been identified as a Python module import.

Workaround:

1. Open the file `import_declare_test.py` located in `$SPLUNK_HOME/etc/apps/TA-MS-AAD/bin`
2. Comment out the `import pwd` line.  It should look like this:
```
import os
#import pwd
import sys
```

3. Restart Splunk

**Comment by saravanakumar-subbiah** [comment] 2022-08-18 08:55
Still I am seeing this error .


Saravanakumar. S
Manager - Security Operations
Hand Phone:8754485958

**Comment by JasonConger** [comment] 2022-09-28 15:20
Addressed in 4.0.3

**Closed by JasonConger** 2022-09-28 15:20 UTC
Labels: status: work in progress
